name: vickidasilva
favicon: null
layout_spectrum: 0.25
typography_spectrum: 0.09121226123534143
title: Vicki DaSilva
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101012'
    - '#dfdfdf'
    - '#373735'
    - '#666664'
    - '#acacaa'
  brandStrength: 0
  lightness: 0.5925438944250345
  saturation: 0.45950927934609354
  rhythmicContrast: 0
purpose: []
